SiteTitle: Statiq
Logo: /assets/statiq.svg
Host: statiq.dev
LinksUseHttps: true
MirrorResources: true
NetlifySiteId: b84df763-be90-43e0-88b7-f0bfcdc0deed
NetlifyAccessToken: => Config.FromSetting<string>("NETLIFY_TOKEN")
SourceFiles:
- ../../Statiq.Framework/src/**/{!.git,!bin,!obj,!packages,!*.Tests,!*.Templates,}/**/*.cs
- ../../Statiq.Web/src/**/{!.git,!bin,!obj,!packages,!*.Tests,!*.Templates,}/**/*.cs
- ../../Statiq.Docs/src/**/{!.git,!bin,!obj,!packages,!*.Tests,!*.Templates,}/**/*.cs
EditRoot: https://github.com/statiqdev/Website/edit/main/input
FontLink: "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&family=Roboto+Slab:wght@400;700&family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Roboto+Thin:wght@200;700&display=swap"
sass-blue: "#48bdfe"
sass-indigo: "#bf4bff"
sass-purple: "#bf4bff"
sass-pink: "#ff5885"
sass-red: "#ff5885"
sass-orange: "#e98f00"
sass-yellow: "#e98f00"
sass-green: "#06c0af"
sass-teal: "#06c0af"
sass-cyan: "#06c0af"
sass-primary: "#0190df"
sass-secondary: "#9300e4"
sass-success: "#035d55"
sass-info: "#035d55"
sass-warning: "#835000"
sass-danger: "#f10041"